# Generated by Django 3.0.5 on 2020-05-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=50)),
                ('client_description', models.TextField()),
                ('staff_description', models.TextField()),
                ('date_start', models.DateField(auto_now_add=True)),
                ('date_end', models.DateField()),
                ('date_finished', models.DateField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Clients')),
            ],
        ),
    ]
