# Generated by Django 3.0.5 on 2020-05-16 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0002_auto_20200513_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Clients'),
        ),
    ]
